# Generated by Django 4.2.1 on 2023-05-12 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Cost Department',
                'verbose_name_plural': 'Cost Departments',
                'db_table': 'cost_departments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('document', models.CharField(max_length=255, verbose_name='Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('cost_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.costdepartment', verbose_name='Cost Department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('document', models.CharField(max_length=255, verbose_name='Document')),
                ('is_provider', models.BooleanField(default=False, verbose_name='Is Provider')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'db_table': 'visitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorIngress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingress_time', models.DateTimeField(auto_now_add=True, verbose_name='Ingress time')),
                ('egress_time', models.DateTimeField(blank=True, null=True, verbose_name='Egress time')),
                ('is_inside', models.BooleanField(default=True, verbose_name='Is inside')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.visitor')),
            ],
            options={
                'verbose_name': 'Visitor Ingress',
                'verbose_name_plural': 'Visitors Ingress',
                'db_table': 'visitors_ingress',
                'ordering': ['-ingress_time'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeIngress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingress_time', models.DateTimeField(auto_now_add=True, verbose_name='Ingress time')),
                ('egress_time', models.DateTimeField(blank=True, null=True, verbose_name='Egress time')),
                ('is_inside', models.BooleanField(default=True, verbose_name='Is inside')),
                ('reason_for_leaving', models.CharField(blank=True, choices=[('CITA', 'Cita médica'), ('CALAMIDAD', 'Calamidad'), ('DILIGENCIA', 'Diligencia personal')], max_length=255, null=True, verbose_name='Reason for leaving')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.employee')),
            ],
            options={
                'verbose_name': 'Employee Ingress',
                'verbose_name_plural': 'Employees Ingress',
                'db_table': 'employees_ingress',
                'ordering': ['-ingress_time'],
            },
        ),
    ]
